spring:
    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
        baseline-version: 1
        validate-on-migrate: true
        encoding: utf-8
    datasource:
        # \u8FD9\u91CC\u8981\u7528MODE\u6307\u5B9A\u6A21\u62DF\u7684\u662Fmysql\u6570\u636E\u5E93\uFF0C\u5426\u5219\u6709\u4E9Bsql\u4F1A\u62A5\u9519
        url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;MODE=MySQL
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
        sql-script-encoding: utf-8
        generate-unique-name: true

